FROM ubuntu:22.04

ARG PYTHON_VERSION="3.8.16"

ARG USER_NAME="rafjar1188"
ARG USER_UID="1000"
ARG USER_GID="1000"

ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y software-properties-common curl wget zip unzip micro \
        build-essential checkinstall libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev && \
    wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz && \
    tar -xf Python-${PYTHON_VERSION}.tgz && \
    cd Python-${PYTHON_VERSION} && \
    ./configure && \
    make install 

RUN rm -rf Python-${PYTHON_VERSION}* && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

RUN groupadd -g ${USER_GID} ${USER_NAME} && \
    useradd -m -g ${USER_GID} -u ${USER_UID} ${USER_NAME}

USER ${USER_UID}:${USER_GID}

RUN mkdir /home/${USER_NAME}/e-biznes

WORKDIR /home/${USER_NAME}/e-biznes
